#!/bin/sh

set -eu

# creating app-manager user if it isn't already there
if ! getent passwd app-manager >/dev/null; then
        adduser --system --force-badname --quiet \
            --no-create-home \
            --home /var/endless \
            --shell /usr/sbin/nologin \
            --group \
            app-manager
fi

#DEBHELPER#

exit 0

